from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Summarize fill CSV generated by the bot.")
    parser.add_argument("--fills", default="data/fills.csv")
    parser.add_argument("--events", default="data/events.jsonl")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    fills_path = Path(args.fills)
    if not fills_path.exists():
        print(f"No fills file found at {fills_path}")
        return
    total_notional = 0.0
    spread_capture = 0.0
    fill_count = 0
    by_market: dict[str, int] = {}
    with fills_path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            fill_count += 1
            size = float(row["size"])
            price = float(row["price"])
            total_notional += size * price
            spread_capture += float(row["spread_capture"] or 0.0)
            by_market[row["market"]] = by_market.get(row["market"], 0) + 1
    round_trip_total = 0.0
    round_trip_spread_only = 0.0
    lottery_count = 0
    events_path = Path(args.events)
    if events_path.exists():
        with events_path.open("r", encoding="utf-8") as handle:
            for line in handle:
                try:
                    event = json.loads(line)
                except Exception:
                    continue
                if event.get("event_type") != "round_trip_pnl":
                    continue
                payload = event.get("payload") or {}
                gross = float(payload.get("gross_pnl") or 0.0)
                is_lottery = bool(payload.get("is_lottery"))
                round_trip_total += gross
                if is_lottery:
                    lottery_count += 1
                else:
                    round_trip_spread_only += gross
    print(f"fills={fill_count}")
    print(f"total_notional_usdc={total_notional:.2f}")
    print(f"estimated_spread_capture_usdc={spread_capture:.2f}")
    if events_path.exists():
        print(f"round_trip_pnl_total_usdc={round_trip_total:.2f}")
        print(f"round_trip_spread_only_usdc={round_trip_spread_only:.2f}")
        print(f"lottery_round_trips={lottery_count}")
    print("fills_by_market:")
    for market, count in sorted(by_market.items(), key=lambda item: item[1], reverse=True):
        print(f"  {market}: {count}")


if __name__ == "__main__":
    main()
